### PR TITLE
First round of cleanup in Common.

### PR DESCRIPTION
**Pull request by pgavlin**

### CODE REVIEW

**Comment by pgavlin** [comment]
@davidsh @stephentoub PTAL

**Comment by pgavlin** [comment]
Ping. Just want to make sure y'all noticed this one.

**Comment by pgavlin** [comment]
@davidsh PTAL--I just realized that I misspelled your GH username earlier :)

**Comment by davidsh** [comment]
LGTM

**Comment by CIPop** [comment]
Hmm.. deja vu in #39?

@pgavlin please confirm (I'm going in order of email threads...)

**Pull request merged**
