### PR TITLE
Clean up the remainder of Interop/Windows/Winsock.

### PR DESCRIPTION
**Pull request by pgavlin**

### CODE REVIEW

**Comment by pgavlin** [comment]
@davidsh, @stephentoub PTAL. Note that pgavlin@4ddc1be is the correct commit to look at--the other commits are part of #39 and earlier.

**Comment by pgavlin** [comment]
Also, note that this concludes the cleanup of System.Net.Sockets. The next step once these PRs are in is to prepare a PR for corefx/master.

**Comment by davidsh** [comment]
LGTM on https://github.com/pgavlin/corefx/commit/4ddc1be

**Comment by pgavlin** [comment]
Once #36 is signed-off on, I think I'll just merge this PR and close the various other individual PRs.

**Comment by CIPop** [comment]
Ah, I get it now: this includes #36 and #39. 
LGTM

@pgavlin Please note that corefx/master already has some of this that I've done for Security.

**Pull request merged**
